### ISSUE TITLE
Random INFO Lock exists! error

### ISSUE THREAD

**Issue by nizardrou** [jerowe/HPC-Runner-Command#21]
With the latest HPCrunner version, I sometimes get this random error
` 2017/08/23 15:06:24: INFO Lock exists!`

An examples of this can be found here,
`/scratch/gencore/170724_SN7001341_0247_BC9RU9ACXX/Unaligned/Project_Edepli_Truseq_RNA/hpc-runner/ncs-89-edepli/logs/2017-08-23-ncs-89-edepli_002_raw_fastqc/2017-08-23-CMD_039-_SID_410042_39_PID_4262.md`

**Comment by nizardrou** [comment]
And another such case,
` 2017/08/23 15:15:55: INFO Lock exists!
 2017/08/23 15:15:56: INFO Lock exists!
 2017/08/23 15:15:56: INFO Lock exists!
 2017/08/23 15:15:57: INFO Lock exists!`

At,
`/scratch/gencore/170724_SN7001341_0247_BC9RU9ACXX/Unaligned/Project_Percipalle/hpc-runner/ncs-89-percipalle/logs/2017-08-23-ncs-89-percipalle_002_raw_fastqc/2017-08-23-CMD_081-_SID_410222_81_PID_11279.md`

**Comment by jerowe** [comment]
Is everything ok besides that? It is actually a debug message, not an error message, but I should have removed it.

**Comment by jerowe** [comment]
I ran a few checks, and everything seems to be fine. 

The lock is for the archive. To ensure hpcrunner gets all the data, across nodes. it creates a lock file. Before it writes to the archive it checks for the existence of the lock file. If a lock file exists it waits .5 seconds, tries again, and repeats that loop 100 times. 

Did you happen to remove the .hpcrunner-data at any time during the run? I am only seeing a portion of the run data.

**Comment by nizardrou** [comment]
No I didn't. And the result is a failed process, so all the jobs with this
warning have actually failed.

**Comment by jerowe** [comment]
I think only the concat_reads failed, which is really bizarre. If you look at `/scratch/gencore/170724_SN7001341_0247_BC9RU9ACXX/Unaligned/Project_Percipalle/hpc-runner/ncs-89-percipalle/logs/2017-08-23-ncs-89-percipalle_003_trimmomatic/ 2017-08-23-CMD_097-_SID_410223_97_PID_14533.md` 

```
 2017/08/23 15:13:31: INFO Lock exists!
 2017/08/23 15:13:31: INFO Lock exists!
 2017/08/23 15:13:33: ERROR TrimmomaticPE: Started with arguments:
```
So it keeps going after the lock file, which is expected behavior.

In any case I updated hpcrunner and have hopefully fixed the problem.

**Comment by jerowe** [comment]
I am rerunning all the jobs, with a different outdir so I don't clobber your results.

**Comment by jerowe** [comment]
I'm going to create a release that rolls back on data archive. I've been battling with it for over 2 months and it just may be more trouble than its worth.

**Comment by jerowe** [comment]
Now that the sqlite plugin seems to be working it may or may not be worth it to even reimplement this, or maybe scale it back. The Logger::JSON API is still useful for integrating with other plugins, so that stays, just not the tar archive.

**Comment by jerowe** [comment]
The Logger::JSON feature was rolled back for 3.2.10, and will be reintroduced in 3.3.10.
