### ISSUE TITLE
HPCrunner aborting

### ISSUE THREAD

**Issue by nizardrou** [jerowe/HPC-Runner-Command#24]
I ran the chipseq deeptools workflow found at,
`/scratch/gencore/workflows/stable/chipseq-noPeaks-deeptools2-human38.yml`

From the following directory,
`/scratch/gencore/170724_SN7001341_0247_BC9RU9ACXX/Unaligned/Project_Percipalle/`

Using the following biox command to generate the hpc script for a subset of samples,
`biox run -w chipseq-noPeaks-deeptools2-human38.yml --samples Sample_In_1 --samples Sample_In_2 --samples Sample_In_3 --samples Sample_P_1 --samples Sample_P_2 --samples Sample_P_3 -o NCB-232-chipSeq-Human.sh`

This validated with no issues, and all output directories were created successfully. Biox reported that everything was in order.

When I then ran the following hpcrunner command,
`hpcrunner.pl submit_jobs --infile NCB-232-chipSeq-Human.sh --project NCB-232-chipSeq-Human`

Nothing is submitted, instead hpcrunner exits with the following error,
`[2017/08/29 15:34:05] Loaded plugin Slurm 
[2017/08/29 15:34:05] Parsing input file 
[2017/08/29 15:34:08] There was a problem creating your schedule. Aborting mission!`

This is the same command that I used successfully earlier today (but with a different workflow and not specifying --samples), and it worked great.

Any ideas?

**Comment by jerowe** [comment]
I will take a look now.

**Comment by jerowe** [comment]
The problem is with the picard_bamindex2 rule.

```
#HPC jobname=picard_bamindex2
#HPC mem=50GB
#HPC commands_per_node=1
#HPC module=gencore gencore_dev gencore_variant_detection/1.0
#HPC partition=serial
#HPC account=gencore
#HPC walltime=12:00:00
#HPC cpus_per_task=1
#HPC deps=picard_bamindex2
```

The job picard_bamindex2 has a dependency on job picard_bamindex2, creating a circular dependency and dying.

There should definetely be an error check for that!

**Comment by nizardrou** [comment]
Ok. I will fix that, but yes it would be good if this is reported in the
biox validation.

Thanks.

**Comment by jerowe** [comment]
I've added this to the 3.3.0 milestone . If the scheduler finds a circular dependency it will report on it.
